Commands are run using a function that reports ok or fail status of each command. Services are started as before. #3

diff --git a/sysconfig/sysinit b/sysconfig/sysinit
--- a/sysconfig/sysinit
+++ b/sysconfig/sysinit
@@ -1,23 +1,28 @@
 #! /bin/ash
 echo "BOXLINUX SYSINIT"
+
+set -e
+
+run () {
+	if $2 ; then
+	    echo "$1 [OK]"
+	else
+	    echo "$1 [FAIL]"
+	fi
+}
+
 date
 uname -srm
-echo "Configuring kernel logging"
-dmesg -n2
-echo "Mounting filesystems"
+run "Kernel logging" "dmesg -n2"
 mkdir -p /dev/pts
-mount -a
-echo "Configuring kernel settings"
-sysctl -qp /etc/sysctl.conf
-echo "Setting hostname"
-hostname -F /etc/hostname
-echo "Starting network"
-ifup -a &>/dev/null
+run "Mounting filesystems" "mount -a"
+run "Kernel settings" "sysctl -qp /etc/sysctl.conf"
+run "Setting hostname" "hostname -F /etc/hostname"
+run "Starting network" "ifup -a"
 echo "Starting services ..."
 echo
 for service in $(ls /var/service)
 do
 	echo " * Starting service $service"
 	runsv /var/service/$service &
-	sleep 1s
 done
